### PR TITLE
Removed `create` prefix

### LINKED ISSUE #1: Remove “create” prefix on Error class
Because we want it to be similar to Message

### PR DESCRIPTION
**Pull request by aradoje**
This will fix #1

### CODE REVIEW

**Comment by Nyholm** [comment]
Ah, great. I just added PrettyC and itI is working.  =)

**Comment by aradoje** [comment]
Yea, It does not allow me to create dummy classes in tests :)

**Comment by Nyholm** [comment]
It does, no worries

**Comment by aradoje** [comment]
I am refactoring it in the next PR. I don't like them in other namespace, if you are gonna make CI pass with them like that I will be happier :)

**Pull request merged**
